[package]
name = "exercises_3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
test_lib = { path = "/home/alien-mega/Documents/Rust_101/exercises/test_lib" }
